### ISSUE TITLE
[PROPOSAL] New instrument for calibration lamps

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera#83]
This proposal is divided in two parts:

1 - Create a new instrument for calibration lamps (i.e. flat field lamps, spectroscopic calibration lamps).

* Implementation suggestion:

```python
def turnOn(self, intensity=100.0):
    #Intensity goes from 1 percent to 100 percent of the capacity, in float numbers.
	return True if successful, otherwise False

def turnOff(self):
	return True if successful, otherwise False

def getState(self):
	return True or intensity if On, otherwise False
```

* Configuration suggestion:

```
calibrationlamp:
   name: flat         # (or flat_Hg, flat_Na)
   type: LNADomeFlat  # (or ArduinoFlat, or WebSocketFlat, ...)
   dome_az: 0         # Azimuth of the dome when taking a calibration image (flat field)
   telescope_alt: 90  # Altitude of the telescope when taking a calibration image
   telescope_az: 45   # Azimuth of the telescope when taking a calibration image
```

If alt, az of dome/telescope are None, there is no need to move the telescope when exposing a calibration frame.

2 - Move the flat field lamp control from the dome to the new instrument. The expected behavior is that when we ask to a calibration frame on a calibration lamp which haves the alt/az properties set, `chimera-cam` must wait for both dome and telescope be on the right position before acquiring a frame.
